Implement forward- and backward mode AD in the interpreter
diku-dk/futhark pull request #2153
Opened 2024-05-30 22:12 UTC by vox9

I'm solely pushing this for code review - I'd need to revise the commits, and clean up the code before I do a real pull request :)

2024-06-02 18:15 UTC, athas requested changes
This is actually pretty good and I am happy with how relatively little code it requires. There is however a pretty long list of style issues to address (and a little functionality things missing, too). I suggest `make check`.

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter.hs
> +              _ -> error "Not implemented (gs3g3ss)" -- TODO: Arrays?
In order to improve the way this is written (and to handle arrays), I suggest defining a utility function for performing a monadic traversal across the "leaves" of an interpreter value. Maybe something with this type:

```Haskell
traverseValue :: Monad f => (PrimValue -> f (Value m)) -> (AD.ADSeed -> f (Value m)) -> Value m -> f (Value m)
```

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter.hs
> +              _ -> error "Not implemented (d19hasd782)" -- TODO: Arrays?
I have a hunch that some functions (like this one) should be factored into their own top-level definitions, to make it easier to understand.

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +data ADSeed
Add a comment remarking on what the meaning of "seed" is (both here and in your implementation in general).

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +  show :: ADSeed -> String
Remove this type signature.

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +valueAsType :: PrimValue -> Rational -> PrimValue
You only ever call this function with a zero value for the `Rational`. There is a notion of `blankPrimValue` that you could use instead.

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +  _ -> Nothing
Instead of using `fromJust` and getting a bad error message, just call `error` directly with an explanation of which `op` failed.

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +typeAsValue :: PrimType -> Rational -> PrimValue
This is almost identical to `valueAsType`. Surely some code can be deduplicated?

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +value :: ADValue -> PrimValue
Call this function `primalValue`. Everything is a "value" in the interpreter!

2024-06-02 18:15 UTC, athas commented on src/Language/Futhark/Interpreter/AD.hs
> +  = TapeId Int ADValue
You convinced me that the `Int` here is necessary (and it is obvious in retrospect), but it is *really* subtle. I suggest coming up with a name for it (too bad "seed" is taken - or is it?).

2024-09-17 10:37 UTC, athas commented
Will this see any further changes?

2024-10-06 14:14 UTC, athas commented
I remember we had a quick chat about this, but I don't remember the outcome. I want to use this for my teaching soon, so unless I hear about changes soon, I'll make the necessary cosmetic fixes myself and merge it.

2024-10-11 14:32 UTC, vox9 commented
(In case you haven't begun,) I will do it today. But from scratch. I've learned a lot from AP, after all!

2024-10-11 14:56 UTC, athas commented
What do you mean "from scratch"? Don't rewrite all the code.

2024-10-11 14:58 UTC, vox9 commented
I'm not going to take a different approach, but I feel that the mess I made when mucking around the code last minute for the exam resulted in something very ugly. Essentially, I'm going through all the code I wrote, and reconsidering it. It should take no more than a day, maybe two, resulting in similar, yet cleaner code. That's fine, right?

2024-10-11 15:23 UTC, athas commented
Up to you, but I will start refactoring this PR on Monday if it's not ready then.

2024-10-13 20:43 UTC, closed without merging